### ISSUE TITLE
should ADDITIONAL_CONFIG be ADDITIONAL_CFG (or vice versa)?

### ISSUE THREAD

**Issue by brobeson** [distributePro/ovsrpro#25]
In *projects/qt5.cmake*, [line 206](https://github.com/distributePro/ovsrpro/blob/17.07.1/projects/qt5.cmake#L206) sets the variable `ADDITIONAL_CONFIG`. [Line 217](https://github.com/distributePro/ovsrpro/blob/17.07.1/projects/qt5.cmake#L217) uses `ADDITIONAL_CFG`. Are these supposed to be the same variable?

**Comment by bnhhughes** [comment]
Good catch, they definitely should be the same variable name - not sure how I managed to spell them differently when they're only 10 lines apart, but here's a pull to fix it: https://github.com/distributePro/ovsrpro/pull/26
