### ISSUE TITLE
There is a typo in the projects readme file

### ISSUE THREAD

**Issue by brobeson** [distributePro/ovsrpro#27]
The link for ZooKeeper in the table isn't rendering properly. There must be a typo in the readme markdown file.

**Comment by bnhhughes** [comment]
I think you  mean ZeroMQ, that's the one that isn't rendering properly, ZooKeeper appears to be fine.  I suggested a fix for this to include with the externpro update.

**Comment by smanders** [comment]
didn't add the necessary "Resolves" keyword in the pull, but this has been resoved by #31
