### ISSUE TITLE
need to disable SSL in librdkafka

### ISSUE THREAD

**Issue by brobeson** [distributePro/ovsrpro#47]
Projects using librdkafka from ovsrpro get a link error. Symbols in libssl cannot be found. A work around is to build ovsrpro, run ccmake in *xpbase/Build/librdkafka_Release*, and turn off `WITH_SSL`. This also needs to be done in *xpbase/Build/librdkafka_Debug*.

Alternatively, we can try to figure out why the symbols cannot be found.

**Comment by bnhhughes** [comment]
Again, not sure why this would be happening, we should be using openssl from within externpro - is this happening even on the "normal" builds or just on the Kubuntu build referenced in https://github.com/distributePro/ovsrpro/issues/46?  It could also be an issue with the changes made a while ago when we moved to the latest externpro and missed some required changes to be able to pull in the openssl stuff from the latest externpro? I would think we could get the SSL stuff to work again if needed, but if it's not worth the effort then we'll just want to make sure we don't have any dependencies to the externpro openssl hanging around.

**Comment by brobeson** [comment]
Downstream projects work without patching librdkafka. This is OBE.
