### ISSUE TITLE
Update librdkafka

### ISSUE THREAD

**Issue by brobeson** [distributePro/ovsrpro#63]

**Comment by swflb** [comment]
after looking at the library, I do not think there are any breaking changes to migrate from v0.9.5 to v1.5.2; the release v1.5.3 might break us as the release notes state that RHEL6 and CentOS6 are EOL. 
I have made some changes and am building ovsrpro. Then i will attempt to test.

**Comment by brobeson** [comment]
We're using CentOS 7, though. Sounds like 1.5.3 should be OK.

**Comment by swflb** [comment]
@brobeson right. i will update to 1.5.3. i want to get a build of the extenpro and your changes to accomodate that before i start a pull request for changes for this ticket.
